<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.vermeerlab</groupId>
        <artifactId>ee-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../ee-parent</relativePath>
    </parent>

    <groupId>org.vermeerlab</groupId>
    <artifactId>ee10-03-db</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <properties>
        <jakarta.version>10.0.0</jakarta.version>
        <microprofile.version>6.1</microprofile.version>
    </properties>

    <!-- flyway -->
    <pluginRepositories>
        <pluginRepository>
            <id>redgate</id>
            <url>https://download.red-gate.com/maven/release</url>
        </pluginRepository>
    </pluginRepositories>
    <!-- flyway -->

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${jakarta.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>${microprofile.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.microprofile-ext.openapi-ext</groupId>
            <artifactId>openapi-ui</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
        </dependency>

        <dependency>
            <groupId>org.vermeerlab</groupId>
            <artifactId>archunit-junit5-plugin</artifactId>
        </dependency>

        <dependency>
            <groupId>org.vermeerlab</groupId>
            <artifactId>base-domain</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.17.2</version>
            <type>jar</type>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.2.224</version>
        </dependency>

        <!-- code scan -->
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.26.1</version>
            <scope>test</scope>
        </dependency>
        <!-- code scan -->

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>com.redgate.flyway</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>10.17.2</version>
                <configuration>
                    <url>jdbc:h2:tcp://localhost:9093/~/appdata</url>
                    <user>sa</user>
                    <password></password>
                    <cleanDisabled>false</cleanDisabled>
                    <locations>
                        <location>classpath:/db/migration/ddl</location>
                        <location>classpath:/db/migration/dml/common</location>
                        <location>${flyway-location}</location>
                    </locations>
                </configuration>
            </plugin>

            <!-- for mvnw （このpluginがないと実行エラーになる） -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>

            <plugin>
                <groupId>org.codehaus.cargo</groupId>
                <artifactId>cargo-maven3-plugin</artifactId>
                <version>1.10.14</version>
                <configuration>
                    <container>
                        <systemProperties>
                            <eclipselink.logging.level>FINE</eclipselink.logging.level>
                        </systemProperties>
                    </container>
                    <configuration>
                        <properties>
                            <cargo.servlet.port>8081</cargo.servlet.port>
                        </properties>
                    </configuration>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <profiles>
        <profile>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <id>payara</id>
            <properties>
                <cargo.maven.containerId>payara</cargo.maven.containerId>
                <cargo.maven.containerUrl>https://repo.maven.apache.org/maven2/fish/payara/distributions/payara/6.2024.5/payara-6.2024.5.zip</cargo.maven.containerUrl>
            </properties>
        </profile>

        <!-- flyway -->
        <profile>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <id>default</id>
            <properties>
                <flyway-location>classpath:/db/migration/dml/dev</flyway-location>
            </properties>
        </profile>
        <profile>
            <id>testDb</id>
            <properties>
                <flyway-location>classpath:/db/migration/dml/test</flyway-location>
            </properties>
        </profile>
        <!-- flyway -->

    </profiles>

</project>
